### ISSUE TITLE
2022 Edition

### ISSUE THREAD

**Issue by flavioribeiro** [flavioribeiro/pastrytown#1]
## 3 Floyds

- [ ] Dark Lord: Marshmallow Handle (BA Imperial Vanilla Stout)
- [ ] Pillar of Beasts (BA Salted Caramel Barleywine)
- [ ] Daytona Stinger (Mojito-Style Wild Ale)
- [ ] Alpha Klaus (Christmas Porter)

## 3 Sons Brewing Co.

- [ ] Lone Star Cake (BA German Chocolate Cake Stout) 
- [ ] BA 3 Monoliths (BA Coconut Coffee Cake Stout)
- [ ] Single Barrel Select: Cali Gold (BA still Barleywine) 
- [ ] Smooth Ops: Piña Colada (Smoothie Seltzer)

## 450 North Brewing Co.

- [ ] Stouty XXL Maple Blueberry Pancakes (Imperial Fruited Stout)
- [ ] Stouty XXL Chocolate Covered Peanut Butter Bananas (Imperial Fruited Stout)
- [ ] Stouty XXL No-Bake Cherry Cheesecake (Imperial Fruited Sour)
- [ ] Slushy Sour (Sour Ale)

## Angry Chair Brewing

- [ ] Barrel Aged Snowball (Imperial Sweet Stout)
- [ ] Maple Cinnamon Bourbon Barrel Aged Fresh Toast (Imperial Porter)
- [ ] Daves Apple Brandy & Vanilla Barleywine (Barrel Aged English Barleywine)

## Arkane Aleworks

- [ ] Deassert Eagle German Cake 2020 BA (Barrel Aged Imperial Stout)
- [ ] Enough To Feed The Needy (Pastry Sour)
- [ ] Hyda Jam (Smoothie Sour)
- [ ] Funzies (Chocolate, Caramel, Peanut Pastry Stout)

## Alvarado Street Brewery

- [ ] The Big Score (BA Stout)
- [ ] Chop & Scrape (BA Stout)
- [ ] Motor Oil 11 (Imperial Stout)
- [ ] Bubble Bath (Hard Smoothie)

## American Solera

- [ ] Good Gorilla (Bourbon Barrel Aged Barleywine with Republic of Congo Vanilla)
- [ ] Full Sized Candy Bar (Rum Barrel Aged Imperial Stout with Coconut)
- [ ] Barrel Aged Dad's Makin Breakfast (Bourbon Barrel Aged Imperial Stout with Coffee, Maple Syrup, Milk Sugar, & Vanilla Beans
- [ ] Caballo Azul (Farmhouse Ale aged in Oak Tanks with Blueberries added)

## Barrel Culture Brewing & Blending

- [ ] Infinite Vanilla (BA Imperial Stout)
- [ ] Oh Heck What the Heck (Bourbon Barrel-Aged Imperial Stout Aged on Chocolate, Strawberry & Vanilla Soft Serve w/ Other Natural Flavors)
- [ ] Heavy Jams: Workin' in My Jammies (Heavily Fruited Sour Ale)

## Bellwoods Brewery

- [ ] Double Barrel Aged Skeleton Key (Spiced Imperial Stout)
- [ ] Jelly King (Dry Hopped Sour w/ Cranberry & Tangerine) 

## Bottle Logic Brewing

- [ ] Tropical Hideaway (Pineapple, Vanilla, Marshmallow Sour Ale)
- [ ] Fomo (BA Vanilla Coffee Stout)
- [ ] Bonzai Break (Acai, Strawberry, Banana, Blueberry, Coconut & Granola Sour Ale)
- [ ] Voltaic Stack (BA Banana Walnut Stout)

## Brooklyn Brewery

- [ ] Brooklyn Black Ops (Russian Imperial Stout)
- [ ] Ruby Can't Fail (Wild Ale)

## Burial Beer Co.

- [ ] The World the Mortals Returned (Imperial Stout with Toasted Pecans, Chocolate & Vanilla Bean
- [ ] A disorientation Along The Path to Nowhere (Imperial Stout with Macadamia, Onyx Coffee, Spicewalla Cinnamon & Vanilla Bean)
- [ ] The Space Where The Supernatural Roam (Imperial Stout with Coconut, Cinnamon, Cocoa Butter, Onyx Kenyan Coffee & Tahitian Vanilla Bean)
- [ ] One of Us Will Have to Bury The Other (Mexican Lager)

## Burley Oak Brewing Company

- [ ] Keg Nog (Imperial Stout)
- [ ] Lil Debbie's (Stout)
- [ ] French Fry Frosty (Imperial Stout)
- [ ] Blueberry, Strawberry, Blackberry, Raspberry, Boysenberry, Marshmallow, Cheesecake, Cobbler, a la mode (Fruited Sour with Lactose)

## Carton Brewing

- [ ] Willet Banana Cream Pie (Imperial Cream Ale Aged in Willet Bourbon Barrels)
- [ ] Pure Yay (Tart IPA)

## Cerebral Brewing

- [ ] Mysterious Forces (Blend 1) (Barrel Aged Imperial Stout)
- [ ] Here be Monsters (2021) (Barrel Aged Imperial Stout)
- [ ] Raven Magic (Barrel Aged Imperial Stout)
- [ ] Exile's Grog (Barrel Aged Tiki Stout)
- [ ] Inhabited Form (Dry Hopped Oat Lager)

## Deciduous Brewing Company

- [ ] Blanket of Stars (Imperial Milk Stout)
- [ ] Frubulous: Strawberry, Raspberry & Blackberry (Heavily Fruited Sour)
- [ ] Frubulous: Dragon Fruit, Mango, Strawberry & Pineapple (Heavily Fruited Sour Ale)

## Dream State

- [ ] Dream State Slumber Party (Pastry Smoothie Sour)
- [ ] Dreaming of Nightmares (Barrel Aged Pastry Stout)

## Dewey Beer

- [ ] Easy Spread (Stout)
- [ ] Cocoaccino Sips (Stout)
- [ ] Apple Caramel (Stout)
- [ ] Thrills Pineapple Orange Vanilla (Fruited)

## Equilibrium Brewery

- [ ] Barrel Aged Peanut Butter Swirl Bar (Imperial Stout Aged in Willett Rye Barrel with Peanuts, Cacao Nibs, Cake Mix & Lactose
- [ ] Life After Death Star (Imperial Stout with Coconut, Marshmallow, Vanilla, Mostra Ghostbear Coffee)
- [ ] Paisley Pattern (Solera Farmhouse Ale with Mango)

## Eighth State Brewing Company

- [ ] Waiting On Forever (Collaboration with Vitamin Sea. Imperial Stout w/ Brown Sugar Cinnamon Poptarts, Coconut, Vanilla & Cassia Bark)
- [ ] Change Your Mind (Collaboration w/ Vitamin Sea. Tequila Staved Sour Ale w/ Passionfruit, Orange, Apricot & Vanilla)
- [ ] Hedylogos (Collaboration with Untitled Art. Cookies & Vanilla Ice Cream Stout)

## Eviltwin Brewing

- [ ] Evil Churros (Imperial Stout)
- [ ] Evil Fusion (Cranberry Apple Vanilla Soft Serve Cobbler Sour Ale, collab with Woven Water Brewing)
- [ ] Banana Split Chocolate Cheesecake (Imperial Stout)
- [ ] Caroline's Over-The-Top Salted Caramel Apple Cider Donut (Pastry Sour Ale)

## Finback Brewery

- [ ] Midnight Beats Pink (Collab with J. Wakefield BA Imperial Stout with Pineapple, Marshmallow, Vanilla, Graham Cracker & Cinnamon)
- [ ] 2020 BQE Coffee + Chocolate (BA Imperial Stout with Coffee & Chocolate)
- [ ] 7 Year Stout (Imperial Stout with Cocoa Nibs & Cocoa Pebbles)
- [ ] 2020 Reaching Skyward (Mixed Culture Sour, Aged in Oak with Peaches)

## Fourscore Beer Co.

- [ ] Soft Swerve: Pink Drank (Heavily Fruited Ice Cream Sour)
- [ ] Beetus Track #2 (Weller Bourbon Barrel Aged Imperial Pastry Stout Conditioned on Coconut, Toasted Coconut, Marcona Almond Cookie & Tahitian Vanilla)
- [ ] Soft Swerve: Blueberry Cream Cheese Pop Tart (Heavily Fruited Ice Cream Sour)
## Froth Brewing Co.

- [ ] Liquid Lollipop (Strawberry, Banana, Cheesecake Triple Fruited Sour)
- [ ] Pastry Town (Bean Bastard Costa Rican Coffee, Peanut Butter, Marshmallow, Madagascar Vanilla Bean Imperial Pastry Stout)

## Great Notion Brewing

- [ ] The Mad Batter (Imperial Pastry Stout)
- [ ] Friends to the End (Imperial Stout)
- [ ] Come Play With Us (Imperial Stout)
- [ ] Big Papaya (Sour)

## Grimm

- [ ] Sumi Noir (Rye Barrel Aged Imperial Stout)
- [ ] No Hands Now (Goes)

## Halfway Crooks

- [ ] Kelvin (German-style Smoked Helles)
- [ ] Radian (German-style Pilsner)

## Harland Brewing Co

- [ ] Banana Q (Barrel Aged Imperial Stout)
- [ ] Haupia (Barrel Aged Imperial Stout)
- [ ] Suede on the Inside (Barrel Aged Imperial Stout)
- [ ] Hydra Fluf (Smoothie style sour)

## Homage Brewing

- [ ] Purple Robots (Barrel Aged Saison w/ Strawberries & Zinfandel Grapes)
- [ ] Comfortable Gestures (Barrel Aged Saison w/ Masumoto Nectarines & Albarino Grapes. Collab with Eighth State)
- [ ] Braindead Saison Spritz (Barrel Aged Saison w/ Blackberry & Syrah Grapes)
- [ ] Saphire & Saturn (Barrel Aged Saison on Sauvignon Blanc Skins)

## Homes Brewery

- [ ] Quad Scoop (BBA Imperial Stout)
- [ ] Permanent HOMES 2021 (BBA Imperial Stout)
- [ ] Apple Pie Smooj (Hard Seltzer Smoothie)
- [ ] Thicc or Treat (Heavily Fruited Sour)

## Hudson Valley Brewery

- [ ] Multichorus Stout (Imperial Stout)
- [ ] Blackberry Peach Glycerin (Sour DIPA)
- [ ] Pink Guava, Red Currant Glycerin (Sour DIPA)
- [ ] Holocene (Sour IPA)

## Horus Aged Ales

- [ ] Proper Dose (Imperial Stout)
- [ ] Coconut Convergence (Imperial Stout)
- [ ] Double Dose (Imperial Stout)
- [ ] bilBerry (Fruited Sour)

## J Wakefield Brewing

- [ ] Royal Immortal (BA Imperial Stout)
- [ ] Everything Floats (BA Imperial Stout)
- [ ] Campfire S'Mores (BA Imperial Stout)
- [ ] Miami Madness (Berliner Weisse)
- [ ] DFPF (Berliner Weisse)
- [ ] Sneaker Sharks (BA Imperial Stout)
- [ ] Nightmare on 24th Street (BA Imperial Stout)

## Kane Brewing Company

- [ ] A Night To End All Dawns: Banana Pancake (Imperial Stout w/ Caramelized Bananas, Maple Syrup & Cinnamon)
- [ ] Painkiller (Fruited Kettle Sour w/ Pineapple, Orange, Coconut & Nutmeg)

## Kings Brewing Co.

- [ ] Field of Kings (Pastry Stout)
- [ ] Blue Mink (B.A. Pastry Stout)

## KCBC

- [ ] Year Five (Barrel Aged Imperial Stout)
- [ ] Maximum Carnage (Fruited Sour)

## Magnify Brewing

- [ ] Pastrytonium (Imperial Stout Collaboration with Equilibrium with Banana & Cinnamon Toast Crunch Cereal)
- [ ] Nerd Squad (Smoothie Sour with Nerds Candy, Vanilla Ice Cream & Strawberry)

## Moksa Brewing Co.

- [ ] Barrel Aged Cremeux (BA Imperial Stout w/ Vanilla)
- [ ] Thiccccest Nibs (BA Imperial Stout w/ Cacao Nibs, Cacao Husks, Cocoa Butter, Vanilla)
- [ ] M7 (BA Imperial Stout w/ Coffee, Vanilla)
- [ ] Let's Lager (Dry Hopped Pilsner)

## Mikerphone Brewing
- [ ] Our Beautiful Dark Twisted Fantasy (Imperial Stout Aged in Willed Rye & Bourbon Whiskey Barrels)
- [ ] Banana Ooh Na Na (Banana Fosters-Inspired Milkshake IPA collab with WeldWerks)

## Mortalis Brewing Co.

- [ ] Pear Brandy Leto (Barrel Aged Stout)
- [ ] Mouth of Madness (Seafood Wax, Barrel Aged Stout)

## Mostra Coffee

- [ ] Cold Brew #1 (Old Rip Van Winkle Barrel Aged Neapolitan Banana Split)
- [ ] Cold Brew #2 (UBE Love with the Coco)

## North Park Beer Co.

- [ ] Bourbon Barrel Aged Nut Butter Macaroons Before Dying (Pastry Stout)
- [ ] Bourbon Barrel Aged Emperor's Macaroons Before Dying (Pastry Stout)
- [ ] Bourbon Barrel Aged Squadron Leader Vanilla Cuvee (Imperial Stout collab with Horus)
- [ ] Bourbon Banana Brûlée (Barrel Fermented Pastry Sour)

## Other Half
- [ ] Pastrytown Sunk 1 - Bourbon BA Blueberry Pancakes

We loaded our bourboon barrel-aged base stout with pancakes, blueberries and maple for this Pastrytown diner classic.

- [ ] Pastrytown Sunk 2 - Bourbon BA Coffee & Waffles (15%)

The Pastrytown Breakfast of Champions. Our Pastrytown base stout aged in a variety of bourbon barrels laced with coffee and stuffed with waffles, maple, coconut and cinnamon.

- [ ] Pastrytown Sunk 3 - Bourbon BA Bananas Foster (15%)

Wild Thai bananas, cinnamon and brown sugar in our bourbon barrel-aged imperial Pastrytown stout recipe. Flambé free.

- [ ]  Pastrytown Sunk 4 - Bourbon BA Rocky Road (15%)

For our Pastrytown dessert course we soaked our bourbon barrel-aged imperial stout with chocolate ice cream, marshmallow and almonds.

- [ ] Pastrytown Sunk - Almond Toffee Brittle (15%)

Brittle goodness without chipping a tooth. Imperial stout brewed with almonds, toffee and chocolate.

- [ ] Pastrytown Sunk - Chocolate Chip Cookie Dough (15%)

We brewed this tubular imperial stout with massive amounts of cookie dough and then upped the flavor with even more cacao nibs and vanilla.

- [ ] Barrel Aged Over One Billion Served (15%)

Bourbon barrel aged pecan chocolate brownie sundae imperial stout with vanilla soft serve ice cream, pecans, cacao nibs and sea salt. 

- [ ] Barrel Aged Over One Trillion Served (15%)

Bourbon barrel aged chocolate brownie sundae imperial stout with chocolate soft serve ice cream and cacao nibs.

- [ ] 22 Month Rum Barrel Aged RUM W'US w/ Three Chiefs Brewing (16%)

Our newest collaboration with our buddies at Three Chiefs Brewing. We reserved some of the base beer from our last collaboration, RUN W'US and aged it in rum barrels for 22 months before crushing it with a ton of chocolate sandwich cookies, hazelnuts, vanilla, and hazelnut coffee.

- [ ] 24 Month Bourbon Barrel Aged Quiet Space w/ Mexican Vera Cruz Vanilla (15.5%)

Quiet Space is a collection of stouts that showcase our finest barrels with minimal high quality adjuncts. For this version, the base was aged in Bourbon barrels for two years before being further aged on Mexican Vera Cruz vanilla. 

- [ ] 18 Month Bourbon Barrel Aged Sunday Crunch w/ Kane (14%)

A mash up of Kane's Brunch Milk Porter and Other Half's Crunchee series. Imperial granola milk porter with coffee, cinnamon, maple, vanilla, toasted coconut, almond and milk sugar.

- [ ] 18 month Bourbon Barrel Aged Pastrinauts w/ J. Wakefield, Bottle Logic, Moksa & Horus

We combined forces with a group of our favorite Pastrinauts to cook up a banana marshmallow astronaut ice cream imperial stout with bananas, molasses, marshmallows and freeze dried ice cream. This version is aged in 15 Year Old 4 Roses Bourbon Barrels. 

- [ ] Barrel Aged Cookie Kooks - Silver Label

We gave our favorite peanut butter cereal mashup a bourbon barrel dunk this year for a very special edition of Silver Label Cookie Kooks. Bourbon barrel aged imperial stout with peanut butter, maple, vanilla, caramel sauce, corn flakes, cookie crisps, cinnamon toast cereal, graham crackers, cocoa cereal, pretzels and milk sugar brewed in collaboration with the always adventurous flavor chemists Omnipollo.

- [ ] Barrel Aged Commander Kooks

Our submariner, Commander Kooks, makes his Pastrytown debut. Once again, we partnered with our friends at Omnipollo for a snickerdoodle garbage cookie ice cream sandwich stout. Bourbon barrel aged imperial stout with snickerdoodle cookies, cinnamon toast cereal, cinnamon churro cereal, corn flakes, vanilla, vanilla ice cream, pretzels, potato chips, caramel, cacao nibs and coffee.

- [ ] DHDHC Mylar Bags DIPA (8.8%)

The beer for hop lovers, now with more hops than last time we added more hops. Mylar bags gets not one but two HDHC treatments for our first, ever DHDHC treatment. Citra, Mosaic, El Dorado, Galaxy, Amarillo Mosaic Cryo and Mosaic Incognito on that next next level.

- [ ] Cannibal Swerve Smoothie Sour w/ Fourscore Beer Co (6.0%)

The Cannibal goes soft-serve for Pastrytown. We joined forces with our friends at Fourscore Beer Co for a mash up of our super fruited smoothie Cannibal series and their big smoothie soft serve, Swerve, series with soft serve ice cream, lychee, dragonfruit, coconut, white grape and milk sugar.

- [ ] TDH Vapor Rings Imperial Oat Cream IPA (8.4%)

We loaded our rig up with even more Citra, Galaxy and Nelson Sauvin hops for a triple dry hopped version on our classic oat cream IPA. Extra pillowy ringz, of oats, raw wheat, and lactose.

- [ ] Triple Broccoli Special Reserve (10%)

Triple Broccoli gets that Special Reserve treatment with Citra in place of Cascade alongside Mosaic, Simcoe and Hallertau Blanc.

- [ ] Tumbleweeds Helles Lager (4.8%)

A follow up to our Crickets series. This lager is hopped lightly with Saphir, it's crispy.

## Parish Brewing co.

- [ ] BA Swamp Stacks (Bourbon Barrel Aged Coconut Smore's Stout)
- [ ] Decade One (Double Barrel Bourbon, Rum, Maple Bourbon, Stout)
- [ ] SIPS: Pinot Noir + Black Currant (Fruited Berliner)

## Phase Three Brewing

- [ ] Eunoia Batch 6 (Barrel Aged Imperial Stout)
- [ ] Eunoia Batch 7 (Barrel Aged Imperial Stout)
- [ ] Lulz: Smoothie: R+R (Smoothie Style Hard Seltzer)

## Prairie Artisan Ales

- [ ] Double Vanilla Noir (Barrel Aged Stout)
- [ ] Moose Boots (Barrel Aged Stout)
- [ ] Christmas Bomb! (Barrel Aged Stout)
- [ ] Tiny Esses (Sour Ale)

## Resident Brewing Co

- [ ] Barrel Aged Morning Sips (Barrel Aged Pastry Stout)
- [ ] Dreams of Autumn

## Resident Culture

- [ ] BBA Same Ghost Every Night w/ Macadamia (BBA Imperial Stout)
- [ ] BBA Twice as Lonely w/ Coffee (BBA Imperial Stout)
- [ ] Squirrel Friends (Fruited Kettle Sour)

## Schilling Beer Co.

- [ ] Augustin 13P (Polotmavy Lager, Czech-style Amber Lager)
- [ ] Landbier (Rustic Agrarian-style Lager)

## Southern Grist Brewing co.

- [ ] Barrel Aged Monotonous & Uncreative OH Collab (BA Stout)
- [ ] Barrel Aged Maple Salted Chocolate Slumber Party Stout (BA Pastry Stout)
- [ ] Barrel Aged Summer of Stouts (BA Stout)
- [ ] Melted Eno-Cone: Black Currant & Raspberry: Extreme Fruited Sour

## Suarez Family Brewery

- [ ] Palatine Pils (Pils)
- [ ] Ms. Frank (Keller Lager)

## Superstition Meadery
- [ ] Pastry Princess (Mead w/ Almond, Coconut, Cacao Nibs & Vanilla)

## Surly Brewing Co.

- [ ] 13 (Maple Barrel Aged Imperial Stout w/ Vanilla & Lactose)
- [ ] Hymn to Beauty (Strawberry, Black Currant Imperial Fruited kettle Sour w/ Vanilla & Lactose)
## Trillium Brewing
- [ ] Coconut PM Dawn (Stout Aged w/ Coconut)
- [ ] Double Pot & Kettle (Barrel-Aged Imperial Oatmeal Porter with vanilla)
- [ ] Barrel-Aged Affogato (Barrel-Aged Imperial Stout with Coffee, Vanilla, Milk Sugar)
- [ ] Daily Serving: Pomegranate & Blackberry (Berliner Weisse w/ Blend of Blackberry & Pomegranate Puree)

## Tripping Animals Brewing

- [ ] Yabadabadu (Ingenious Collab Pastry Sour)
- [ ] Quesillo For Days #3 (Equilibrium Collab Rum BA Stout)

## Toppling Goliath Brewing Co.

- [ ] Mornin' Delight
- [ ] Term-Oil Mostra 7th Anniversary (BA Imperial Stout)
- [ ] Term-Oil Fluffernutter (BA Imperial Stout)
- [ ] Cherry Fandango (Kettle Sour)

## Two Tides Brewing Co.

- [ ] How Much Cheese is Too Much Cheese (Imperial Stout)
- [ ] What? (Imperial Stout)
- [ ] Layerz (Sour)

## Urban South Brewery

- [ ] Twain Twacks (Pastry Stout)
- [ ] Blue Light (Imperial Stout)
- [ ] Spilled (Overly Fruited Sour)

## The Veil Brewing Co.

- [ ] Big Royale Nut Bar Crunch (Barrel Aged Imperial Stout conditioned on macadamia nuts, hazelnuts, peanut, coconut and vanilla)
- [ ] Starve: Exhibit D (Barrel Aged Imperial Stout w/ Honey, Vanilla & Marshmallows)
- [ ] Cinnabon Lord Whangdoodle (Barrel Aged Imperial Chocolate Milk Stout w/ Chocolate Sandwich Cookies, Maple Syrup, Cinnamon, Vanilla, Caramel & Toffee)
- [ ] The Weapon: Exhibit D (Sour Double India Pale Ale with Milk Sugar, Blueberry & Raspberry)

## Vitamin Sea Brewing

- [ ] Company Week Keep (Imperial Pastry Stout)
- [ ] Lost in Translation (Imperial Coffee Stout)
- [ ] Sinking Ships (Imperial Pastry Stout)
- [ ] Sour Pipe Project Orange Cream Pop (Fruited Sour)

## Voodoo Brewing Co.

- [ ] Black Magick Aged in Bourbon Barrels (Imperial Sour Curt's BRC era Black Magick Aged over 27 months in Blanton's Bourbon Barrels)
- [ ] Aphotic Aged in Cherry Brandy Barrels (Imperial Stout Aphotic aged 27 months in French Oak Cherry Brandy Barrels)
- [ ] Florida Stout (Conditioned on Strawberry & Cacao) Our Imperial Pastry/Sweet Stout that showcases rotating adjuncts, the name paying homage to the style that was popularized by many of our friends in the sunshine state)
- [ ] Lacto-Kooler, Green ( Sour Berliner Weisse Style w/ Green)

## WeldWerks Brewing

- [ ] BA Breakfast for Four (Barrel Aged Stout)
- [ ] Pastrytown Exclusive Medianoche: Sopapina Cheesecake (Barrel Aged Imperial Stout)
- [ ] Little Man Salted Oreo Stout (Stout)
- [ ] Pumpkin Pie Cheesecake Berliner (Berliner)

## Weathered Souls Brewing
- [ ] Double Barrel Whale Rider (Imperial Stout w/ Toasted Coconut, Coconut, Madagascar Vanilla Beans. Double barreled in an 8-year willed rye barrel & 15-year Woodford reserve masters barrel)
- [ ] Rainbow Sherbet (Berliner style sour w/ oranges, strawberries & lime)
- [ ] Pitch Hitter (Barrel Aged Imperial Stout aged in an 8-year willed WFE Rye Barrel & Thomas H Handy Barrels w/ Brownie Batter, Mexican Vanilla Beans, Tanzania Vanilla Beans, Cacao Husk & Hazelnuts)

## Woven Water Brewing Co.

- [ ] BA Obsidius (Barrel Aged Stout)
- [ ] Haddonfield (Imperial Stout)
- [ ] Peanut Butter & Jelly Sandwich Fusion (Super Fruited Sour Ale)

**Comment by flavioribeiro** [comment]
missing https://www.instagram.com/p/CV6OGx1JZbQ/
